name: Swift

on: push

jobs:
    Build_and_Test:
    
        runs-on: macos-latest
        
        steps:
        - uses: actions/checkout@v2
        - name: Build
          run: swift build --build-tests --disable-automatic-resolution -v
        - name: Run tests
          run: swift test --disable-automatic-resolution -v
